### PR TITLE
bump build number for new build

### LINKED ISSUE #6: I think it might be time to re-render this
Issue:
Installing into an existing & recent conda-forge-only environment via `conda install pytest-pep8 --channel=conda-forge` takes a very long time and has conflicts with setuptools.

I don't know this, but it seems like a re-render to freshen up the builds should do the trick. I'll take a stab at that.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by phobson**
Closes #6 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by phobson** [comment]
@nicoddemus thanks for the re-render! I was digging through my old PRs in other feedstocks to find the right incantation

**Comment by phobson** [comment]
Thanks for the quick merge!

**Comment by isuruf** [comment]
cc @bjodah, @ocefpaf, ref: https://github.com/conda-forge/pytest-cache-feedstock/issues/3

**Pull request merged**
